receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource/something:
    attributes:
      - key: something
        value: something
        action: insert

service:
  pipelines:
    logs/something:
      receivers:
        - otlp
      processors:
        - resource/something
      exporters:
        - abstract
        - sumologic
        - elastic
        - etc
        - etc
